[package]
name = "urd"
version = "0.2.0"
edition = "2021"
authors = ["Xqhare"]
license = "EPL-2.0"

[profile.release]
lto = "fat"

[dependencies]
eframe = "0.29.1"
horae = { git = "https://github.com/xqhare/horae" }
